# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Lint and Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  # Run linter check. Only test code linters on latest version of Go.
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20
        id: go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20

      - uses: actions/checkout@v4
        with:
          submodules: false

      - run: make lint

  # Run tests against latest Go version.
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20
        id: go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20

      - uses: actions/checkout@v4
        with:
          submodules: false

      - run: make test

  # Run build with latest Go version.
  make:
    name: Make all
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20
        id: go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20

      - uses: actions/checkout@v4
        with:
          submodules: false

      - run: make all
